<a href="https://colab.research.google.com/github/ENSB-Projects/ML-Workshop-QSAR/blob/main/ML_Worshop_QSAR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1) Data Collection

In [7]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 1.1) Search ChEMBL Database

### 1.1.1) Install ChEMBL Library

In [1]:
!pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.2-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.5.20)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.10.0)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 3.3 MB/s eta 0:00:00
Downloading requests_cache-1.3.2-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.6/70.6 kB 6.6 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.6 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.1.0 chembl_webresource_client-0.10.9 requests-cache-1.3.2 url-normalize-3.0.0

### 1.1.2) Import ChEMBL Library

In [2]:
from chembl_webresource_client.new_client import new_client

### 1.1.3) Search for Target Protein

In [3]:
target = new_client.target
target_query = target.search('aromatase')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Homo sapiens,Aromatase,20.0,False,CHEMBL1978,"[{'accession': 'P11511', 'component_descriptio...",SINGLE PROTEIN,9606
1,[],Rattus norvegicus,Aromatase,19.0,False,CHEMBL3859,"[{'accession': 'P22443', 'component_descriptio...",SINGLE PROTEIN,10116
2,[],Homo sapiens,von Hippel-Lindau disease tumor suppressor/Aro...,16.0,False,CHEMBL6066122,"[{'accession': 'P11511', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

In [4]:
selected_target = targets['target_chembl_id'][0]
selected_target

'CHEMBL1978'

### 1.1.4) Get Target Bioactivities

In [5]:
activity = new_client.activity
Results = activity.filter(target_chembl_id = selected_target).filter(standard_type = 'IC50')

In [12]:
data = pd.DataFrame.from_dict(Results)
data

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,82585,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,7.1
1,None,None,94540,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,50.0
2,None,None,112960,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.238
3,None,None,116766,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.057
4,None,None,118017,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4408,None,1240259,28894436,[],CHEMBL5738928,Inhibition Assay: The compounds were tested fo...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,14500.0
4409,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29176245,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6110984,Inhibition of aromatase in human MCF7 cells us...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,64.9
4410,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29176246,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6110984,Inhibition of aromatase in human MCF7 cells us...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,1850.0
4411,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29193884,[],CHEMBL6116726,Inhibition of aromatase (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.5
4412,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29193885,[],CHEMBL6116726,Inhibition of aromatase (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,45.0

## 1.2) Or Open CSV file from Google Drive

In [8]:
from google.colab import  drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
data = pd.read_csv('/content/drive/MyDrive/Data.csv', sep =';')
data

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL1397,POSACONAZOLE,4.0,700.79,2.0,4.57,Posaconazole,CC[C@@H]([C@H](C)O)n1ncn(-c2ccc(N3CCN(c4ccc(OC...,IC50,'=',...,CHEMBL4052712,1,Scientific Literature,Bioorg Med Chem Lett,2017,NaN,NaN,NaN,NaN,8.40
1,CHEMBL275594,NaN,NaN,232.28,0.0,1.56,7,CCCC1(c2ccncc2)CCC(=O)NC1=O,IC50,'=',...,CHEMBL1123885,1,Scientific Literature,J Med Chem,1987,NaN,NaN,NaN,NaN,6.00
2,CHEMBL168444,NaN,NaN,254.29,0.0,1.96,8,O=C1c2ccccc2CCC1C(O)c1ccncn1,IC50,'=',...,CHEMBL1129578,1,Scientific Literature,J Med Chem,1996,NaN,NaN,NaN,NaN,27.00
3,CHEMBL223452,NaN,NaN,296.33,0.0,3.40,T42,N#Cc1ccc(C(c2ccc(C#N)cc2)c2cncnc2)cc1,IC50,'=',...,CHEMBL1139479,1,Scientific Literature,J Med Chem,2005,NaN,NaN,NaN,NaN,6.54
4,CHEMBL375043,NaN,NaN,233.27,0.0,2.96,T29,N#Cc1ccc(Cn2ccnc2)c2ccccc12,IC50,'=',...,CHEMBL1139479,1,Scientific Literature,J Med Chem,2005,NaN,NaN,NaN,NaN,7.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4408,CHEMBL5808901,NaN,NaN,374.40,0.0,3.28,BDBM582683,O=C1COc2cc(NCc3cccc(C(=O)Nc4cccnc4)c3)ccc2N1,IC50,'=',...,CHEMBL5729535,37,BindingDB Patent Bioactivity Data,NaN,2023,NaN,NaN,NaN,NaN,5700.00
4409,CHEMBL5873947,NaN,NaN,442.30,1.0,5.19,BDBM582675,O=C1COc2cc(NCc3cccc(NC(=O)c4ccccc4Cl)c3)c(Cl)c...,IC50,'>',...,CHEMBL5729535,37,BindingDB Patent Bioactivity Data,NaN,2023,NaN,NaN,NaN,NaN,25000.00
4410,CHEMBL5946526,NaN,NaN,350.40,0.0,1.46,BDBM582666,Cc1cccc(C(=O)OCCOc2ccc(S(N)(=O)=O)cc2)c1N,IC50,'=',...,CHEMBL5729535,37,BindingDB Patent Bioactivity Data,NaN,2023,NaN,NaN,NaN,NaN,43500.00
4411,CHEMBL6167931,NaN,NaN,431.53,0.0,3.77,6a,CC(C)(C)c1ccc(S(=O)(=O)N2CCN(Cc3nc4cc(F)ccc4o3...,IC50,'=',...,CHEMBL6109100,1,Scientific Literature,Bioorg Med Chem,2025,NaN,TIME = 2.0 hr,INHIBITOR,NaN,64.90
4412,CHEMBL5887888,NaN,NaN,408.85,0.0,3.93,BDBM582699,O=C1COc2cc(NCc3cccc(C(=O)Nc4cccnc4)c3)c(Cl)cc2N1,IC50,'=',...,CHEMBL5729535,37,BindingDB Patent Bioactivity Data,NaN,2023,NaN,NaN,NaN,NaN,14500.00

In [10]:
data.columns

Index(['Molecule ChEMBL ID', 'Molecule Name', 'Molecule Max Phase',
       'Molecular Weight', '#RO5 Violations', 'AlogP', 'Compound Key',
       'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value',
       'Standard Units', 'pChEMBL Value', 'Data Validity Comment', 'Comment',
       'Uo Units', 'Ligand Efficiency BEI', 'Ligand Efficiency LE',
       'Ligand Efficiency LLE', 'Ligand Efficiency SEI', 'Potential Duplicate',
       'Assay ChEMBL ID', 'Assay Description', 'Assay Type', 'BAO Format ID',
       'BAO Label', 'Assay Organism', 'Assay Tissue ChEMBL ID',
       'Assay Tissue Name', 'Assay Cell Type', 'Assay Subcellular Fraction',
       'Assay Parameters', 'Assay Variant Accession', 'Assay Variant Mutation',
       'Target ChEMBL ID', 'Target Name', 'Target Organism', 'Target Type',
       'Document ChEMBL ID', 'Source ID', 'Source Description',
       'Document Journal', 'Document Year', 'Cell ChEMBL ID', 'Properties',
       'Action Type', 'Standard Text Value', 'Value'],
      dtype='object')

# 2) Data Pre-processing

## 2.1) Handling missing data

### 2.1.1) Delete rows without standard value and SMILES

In [13]:
(data['standard_value'].notna()).value_counts()
# Utiliser cette instruction dans le cas de lecture du fichier CSV de Google Drive
#(data['Standard Value'].notna()).value_counts()

standard_value
True     4319
False      94
Name: count, dtype: int64

In [14]:
(data['canonical_smiles'].notna()).value_counts()
# Utiliser cette instruction dans le cas de lecture du fichier CSV de Google Drive
#(data['Smiles'].notna()).value_counts()

canonical_smiles
True    4413
Name: count, dtype: int64

In [15]:
data2 = data[data['standard_value'].notna()]
data2 = data2[data2['canonical_smiles'].notna()]
# Utiliser ces instructiosn dans le cas de lecture du fichier CSV de Google Drive
#data2 = data[data['Standard Value'].notna()]
#data2 = data2[data2['Smiles'].notna()]
data2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,82585,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,7.1
1,None,None,94540,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,50.0
2,None,None,112960,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.238
3,None,None,116766,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.057
4,None,None,118017,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4408,None,1240259,28894436,[],CHEMBL5738928,Inhibition Assay: The compounds were tested fo...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,14500.0
4409,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29176245,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6110984,Inhibition of aromatase in human MCF7 cells us...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,64.9
4410,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29176246,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6110984,Inhibition of aromatase in human MCF7 cells us...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,1850.0
4411,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29193884,[],CHEMBL6116726,Inhibition of aromatase (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.5
4412,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29193885,[],CHEMBL6116726,Inhibition of aromatase (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,45.0

In [16]:
data2.reset_index(drop = True, inplace = True)
data2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,82585,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,7.1
1,None,None,94540,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,50.0
2,None,None,112960,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.238
3,None,None,116766,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.057
4,None,None,118017,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4314,None,1240259,28894436,[],CHEMBL5738928,Inhibition Assay: The compounds were tested fo...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,14500.0
4315,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29176245,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6110984,Inhibition of aromatase in human MCF7 cells us...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,64.9
4316,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29176246,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6110984,Inhibition of aromatase in human MCF7 cells us...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,1850.0
4317,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29193884,[],CHEMBL6116726,Inhibition of aromatase (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.5
4318,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29193885,[],CHEMBL6116726,Inhibition of aromatase (unknown origin),B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,45.0

## 2.2) Delete duplicated SMILES

In [17]:
len(data2.canonical_smiles.unique())
# Utiliser cette instruction dans le cas de lecture du fichier CSV de Google Drive
#len(data2.Smiles.unique())

3130

In [18]:
data3 = data2.drop_duplicates('canonical_smiles')
# Utiliser cette instruction dans le cas de lecture du fichier CSV de Google Drive
#data3 = data2.drop_duplicates('Smiles')
data3.reset_index(drop = True, inplace = True)
data3

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,82585,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,7.1
1,None,None,94540,[],CHEMBL666794,Inhibition of Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,50.0
2,None,None,112960,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.238
3,None,None,116766,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.057
4,None,None,118017,[],CHEMBL661700,In vitro inhibition of human Cytochrome P450 19A1,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,uM,UO_0000065,None,0.054
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3125,None,1240239,28894376,[],CHEMBL5738928,Inhibition Assay: The compounds were tested fo...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,5700.0
3126,None,1240245,28894394,[],CHEMBL5738928,Inhibition Assay: The compounds were tested fo...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,8600.0
3127,None,1240252,28894415,[],CHEMBL5738928,Inhibition Assay: The compounds were tested fo...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,60.0
3128,None,1240259,28894436,[],CHEMBL5738928,Inhibition Assay: The compounds were tested fo...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,14500.0
3129,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29176245,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6110984,Inhibition of aromatase in human MCF7 cells us...,B,None,None,BAO_0000190,...,Homo sapiens,Aromatase,9606,None,None,IC50,nM,UO_0000065,None,64.9

## 2.3) Select 3 columns : ID, SMILES and IC50

In [19]:
data3.columns

Index(['action_type', 'activity_comment', 'activity_id', 'activity_properties',
       'assay_chembl_id', 'assay_description', 'assay_type',
       'assay_variant_accession', 'assay_variant_mutation', 'bao_endpoint',
       'bao_format', 'bao_label', 'canonical_smiles', 'data_validity_comment',
       'data_validity_description', 'document_chembl_id', 'document_journal',
       'document_year', 'ligand_efficiency', 'modality', 'molecule_chembl_id',
       'molecule_pref_name', 'parent_molecule_chembl_id', 'pchembl_value',
       'potential_duplicate', 'qudt_units', 'record_id', 'relation', 'src_id',
       'standard_flag', 'standard_relation', 'standard_text_value',
       'standard_type', 'standard_units', 'standard_upper_value',
       'standard_value', 'target_chembl_id', 'target_organism',
       'target_pref_name', 'target_tax_id', 'text_value', 'toid', 'type',
       'units', 'uo_units', 'upper_value', 'value'],
      dtype='object')

In [20]:
selected_columns = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
# Utiliser cette instruction dans le cas de lecture du fichier CSV de Google Drive
#selected_columns = ['Molecule ChEMBL ID', 'Smiles', 'Standard Value']
data4 = data3[selected_columns]
data4

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL341591,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12,7100.0
1,CHEMBL2111947,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,50000.0
2,CHEMBL431859,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21,238.0
3,CHEMBL113637,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21,57.0
4,CHEMBL112021,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21,54.0
...,...,...,...
3125,CHEMBL5808901,O=C1COc2cc(NCc3cccc(C(=O)Nc4cccnc4)c3)ccc2N1,5700.0
3126,CHEMBL5916153,O=C1COc2cc(NCc3cccc(C(=O)Nc4ccccc4O)c3)ccc2N1,8600.0
3127,CHEMBL5875159,O=C1COc2cc(NC(=O)c3cc(NC(=O)c4cn[nH]c4)ccc3Cl)...,60.0
3128,CHEMBL5887888,O=C1COc2cc(NCc3cccc(C(=O)Nc4cccnc4)c3)c(Cl)cc2N1,14500.0
3129,CHEMBL6167931,CC(C)(C)c1ccc(S(=O)(=O)N2CCN(Cc3nc4cc(F)ccc4o3...,64.9

In [21]:
data4.rename(columns = {'standard_value':'IC50', 'molecule_chembl_id':'ID', 'canonical_smiles':'SMILES'}, inplace = True)
# Utiliser cette instruction dans le cas de lecture du fichier CSV de Google Drive
#data4.rename(columns = {'Standard Value':'IC50', 'Molecule ChEMBL ID':'ID'}, inplace = True)
data4

/tmp/ipykernel_3236/270839843.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data4.rename(columns = {'standard_value':'IC50', 'molecule_chembl_id':'ID', 'canonical_smiles':'SMILES'}, inplace = True)

,ID,SMILES,IC50
0,CHEMBL341591,CC12CCC(O)CC1=CCC1C2CCC2(C)C(CC3CN3)CCC12,7100.0
1,CHEMBL2111947,C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@@]43...,50000.0
2,CHEMBL431859,CCn1c(C(c2ccc(F)cc2)n2ccnc2)c(C)c2cc(Br)ccc21,238.0
3,CHEMBL113637,CCn1cc(C(c2ccc(F)cc2)n2ccnc2)c2ccccc21,57.0
4,CHEMBL112021,Clc1ccccc1Cn1cc(Cn2ccnc2)c2ccccc21,54.0
...,...,...,...
3125,CHEMBL5808901,O=C1COc2cc(NCc3cccc(C(=O)Nc4cccnc4)c3)ccc2N1,5700.0
3126,CHEMBL5916153,O=C1COc2cc(NCc3cccc(C(=O)Nc4ccccc4O)c3)ccc2N1,8600.0
3127,CHEMBL5875159,O=C1COc2cc(NC(=O)c3cc(NC(=O)c4cn[nH]c4)ccc3Cl)...,60.0
3128,CHEMBL5887888,O=C1COc2cc(NCc3cccc(C(=O)Nc4cccnc4)c3)c(Cl)cc2N1,14500.0
3129,CHEMBL6167931,CC(C)(C)c1ccc(S(=O)(=O)N2CCN(Cc3nc4cc(F)ccc4o3...,64.9

In [ ]:
data4.info()

In [ ]:
data4 = data4.convert_dtypes()
data4.info()

In [ ]:
data4['IC50'] = data4['IC50'].astype(float)
data4.info()

In [ ]:
(data4['IC50'] == 0).value_counts()

In [ ]:
data4['IC50'].describe()

In [ ]:
data5 = data4[data4['IC50'] != 0]
data5.reset_index(drop = True, inplace = True)
data5

## 2.4) Calculate pIC50

In [ ]:
def pIC50(DF):
  p_values = []
  for i in DF['IC50']:
    if i > 100000000:
      i = 100000000
    molar = i * (10 ** -9)
    p = -np.log10(molar)
    p_values.append(p)
  DF['pIC50'] = p_values
  DF2 = DF.drop('IC50', axis = 1)
  return DF2

In [ ]:
data6 = pIC50(data5)
data6

In [ ]:
data6['pIC50'].describe()

# 3) Exploratory Data Analysis

## 3.1) Install RDKIT Library

In [ ]:
!pip install rdkit

## 3.2) Import modules from RDKIT library

In [ ]:
from rdkit import Chem
from rdkit.Chem import Descriptors, Lipinski

## 3.3) Calculate Lipinski descriptors

In [ ]:
def lipinski(smiles):

    moldata= []
    for elem in smiles:
        mol=Chem.MolFromSmiles(elem)
        moldata.append(mol)

    baseData= np.arange(1,1)
    i=0
    for mol in moldata:

        desc_MolWt = Descriptors.MolWt(mol)
        desc_MolLogP = Descriptors.MolLogP(mol)
        desc_NumHDonors = Lipinski.NumHDonors(mol)
        desc_NumHAcceptors = Lipinski.NumHAcceptors(mol)

        row = np.array([desc_MolWt,
                        desc_MolLogP,
                        desc_NumHDonors,
                        desc_NumHAcceptors])

        if(i==0):
            baseData=row
        else:
            baseData=np.vstack([baseData, row])
        i=i+1

    columnNames=["MW","LogP","NumHDonors","NumHAcceptors"]
    descriptors = pd.DataFrame(data=baseData,columns=columnNames)

    return descriptors

In [ ]:
Smiles = data6['SMILES']
Lipinski_Descriptors = lipinski(Smiles)
Lipinski_Descriptors

In [ ]:
data_combined = pd.concat([data6, Lipinski_Descriptors], axis=1)
data_combined

In [ ]:
data_combined.pIC50.describe()

In [ ]:
Activity = []
for p in data_combined['pIC50']:
  if p >= 6:
    Activity.append('Active')
  else:
    Activity.append('Inactive')
data_combined['Class'] = Activity
data_combined

## 3.4) Generate plots

### 3.4.1) Histograms

In [ ]:
p_values = np.array(data_combined['pIC50'])
n, bin, patches = plt.hist(p_values, 50, density = True,
                           facecolor = 'g', alpha = 0.75)
plt.xlabel('pIC50 values')
plt.ylabel('Molecules number')
plt.title('Histogram of pIC50')
plt.grid(True)
plt.show()

In [ ]:
sns.countplot(data = data_combined, x = 'Class')
plt.xlabel('Class')
plt.ylabel('Molecules number')
plt.title('Histrogram of Activity Class')
plt.show()

In [ ]:
data_combined['Class'].value_counts()

### 3.4.2) Boxplots

In [ ]:
sns.boxplot(x = data_combined['Class'], y = data_combined['MW'])
plt.title("Boxplot on Molecular Weight")
plt.show()

In [ ]:
sns.boxplot(x = data_combined['Class'], y = data_combined['LogP'])
plt.title("Boxplot on LogP")
plt.show()

In [ ]:
sns.boxplot(x = data_combined['Class'], y = data_combined['NumHDonors'])
plt.title("Boxplot on NumHDonors")
plt.show()

In [ ]:
sns.boxplot(x = data_combined['Class'], y = data_combined['NumHAcceptors'])
plt.title("Boxplot on NumHAcceptors")
plt.show()

### 3.4.3) Scatterplot

In [ ]:
g = sns.scatterplot(data = data_combined, x = 'MW', y = 'LogP',
                    hue = 'Class', size = 'pIC50')
sns.move_legend(g, 'upper left',
                bbox_to_anchor = (1, 1), title = 'Class')
plt.title("Scatterplot on Molecular Weight and LogP")
plt.show()

## 3.5) Statistical Test (nonparametric test : Mann-Whitney U Test)

In [ ]:
def mannwhitney(descriptor):
  from numpy.random import seed
  from numpy.random import randn
  from scipy.stats import mannwhitneyu

# seed the random number generator
  seed(1)

# actives and inactives
  selection = [descriptor, 'Class']
  df14 = data_combined[selection]

  active = df14[df14['Class'] == 'Active']
  active = active[descriptor]

  inactive = df14[df14['Class'] == 'Inactive']
  inactive = inactive[descriptor]

# compare samples
  stat, p = mannwhitneyu(active, inactive)
  #print('Statistics=%.3f, p=%.3f' % (stat, p))

# interpret
  alpha = 0.05
  if p > alpha:
    interpretation = 'Same distribution (fail to reject H0)'
  else:
    interpretation = 'Different distribution (reject H0)'

  results = pd.DataFrame({'Descriptor':descriptor,
                          'Statistics':stat,
                          'p':p,
                          'alpha':alpha,
                          'Interpretation':interpretation}, index=[0])
  filename = 'mannwhitneyu_' + descriptor + '.csv'
  results.to_csv(filename)

  return results

In [ ]:
mannwhitney('pIC50')

In [ ]:
mannwhitney('MW')

In [ ]:
mannwhitney('LogP')

In [ ]:
mannwhitney('NumHDonors')

In [ ]:
mannwhitney('NumHAcceptors')

# 4) Descriptors Generation

## 4.1) Install PADELPy Library

In [ ]:
!pip install padelpy

In [ ]:
# Download fingerprint XML files
! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
! unzip fingerprints_xml.zip

In [ ]:
# List and sort fingerprint XML files
import glob
xml_files = glob.glob("*.xml")
xml_files.sort()
xml_files

FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

# Create a dictionary
fp = dict(zip(FP_list, xml_files))

df = pd.concat([data_combined['SMILES'], data_combined['ID']], axis=1 )
df.to_csv('molecules.smi', sep='\t', index=False, header=False)
df

## 4.2) Generate Fingerprints

In [ ]:
# To fix the Java JRE 6+ not found error, run this command line
!apt-get install -y openjdk-11-jre-headless

In [ ]:
from padelpy import padeldescriptor
padeldescriptor(mol_dir = "molecules.smi",
             d_file = 'PubChem_descriptors.csv',
             descriptortypes = fp['PubChem'],
             detectaromaticity = True,
             standardizetautomers = True,
             threads = 2,
             removesalt = True,
             log = True,
             fingerprints = True)

In [ ]:
Descriptors = pd.read_csv('PubChem_descriptors.csv')
Descriptors

In [ ]:
Descriptors.drop("Name", axis = 1 , inplace = True)
Descriptors

# 5) Feature Selection

In [ ]:
from sklearn.feature_selection  import VarianceThreshold
selection = VarianceThreshold(threshold = (0.8 * (1 - 0.8)))
X = selection.fit_transform(Descriptors)
X

In [ ]:
Y = data_combined['pIC50']
Y

# 6) Model Training

## 6.1) Split the dataset into Train/Test sets

In [ ]:
from sklearn.model_selection import train_test_split
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, train_size = 0.8,
                                                    test_size = 0.2)

In [ ]:
X.shape, Y.shape

In [ ]:
X_Train.shape, Y_Train.shape

In [ ]:
X_Test.shape, Y_Test.shape

## 6.2) Train the model

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators = 10)
model.fit(X_Train, Y_Train)

In [ ]:
Y_Pred = model.predict(X_Test)
Y_Pred

# 7) Model Evaluation

In [ ]:
from sklearn import metrics

In [ ]:
R2 = metrics.r2_score(Y_Test, Y_Pred)
MSE = metrics.mean_squared_error(Y_Test, Y_Pred)
RMSE = np.sqrt(MSE)
MAE = metrics.mean_absolute_error(Y_Test, Y_Pred)
MAPE = metrics.mean_absolute_percentage_error(Y_Test, Y_Pred)
Max_Error = metrics.max_error(Y_Test, Y_Pred)
print("R2 = ", round(R2, 3))
print("MSE = ", round(MSE, 3))
print("RMSE = ", round(RMSE, 3))
print("MAE = ", round(MAE, 3))
print("MAPE = ", round(MAPE, 3))
print("Max_Error = ", round(Max_Error, 3))

In [ ]:
sns.set(color_codes=True)
sns.set_style("white")

ax = sns.regplot(x= Y_Test, y = Y_Pred, scatter_kws={'alpha':0.4})
ax.set_xlabel('Experimental pIC50', fontsize='large', fontweight='bold')
ax.set_ylabel('Predicted pIC50', fontsize='large', fontweight='bold')
ax.set_xlim(0, 12)
ax.set_ylim(0, 12)
ax.figure.set_size_inches(5, 5)
plt.show()

# 8) Feature Importance

In [ ]:
mask = selection.get_support()
selected_columns_indices = [i for i, f in enumerate(mask) if f]
features = Descriptors.columns[selected_columns_indices]
features

In [ ]:
features.shape , len(selected_columns_indices)

In [ ]:
importances = model.feature_importances_
best_indices = np.argsort(importances)[-5:]
worst_indices = np.argsort(importances)[:5]
indices = np.concatenate([worst_indices, best_indices])

plt.figure(figsize=(10,8))
plt.title('10 Most and 10 Least Important Features in the Model')
plt.barh(range(len(indices)), importances[indices], color='b', align='center')
plt.yticks(range(len(indices)), [features[i] for i in indices])
plt.xlabel('Relative Importance')
plt.ylabel('Feature Name')
plt.show()